[build]
  command = "npm run build"
  publish = "."

[dev]
  command = "npm run dev"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.xml"
  [headers.values]
    Cache-Control = "public, max-age=86400"